// <auto-generated />
namespace Desafio1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tablaval : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablaval));
        
        string IMigrationMetadata.Id
        {
            get { return "202309082137286_tablaval"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
